In [11]:
# import dependencies

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

# 4.
from citipy import citipy

import requests

# 5.
# Import the API key.
from config import weather_api_key

# Import the time library and the datetime module from the datetime library 
import time
from datetime import datetime

In [12]:
# 3. Create a new set of 2,000 random latitudes and longitudes.

# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs

# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [8]:
# 4. Get the nearest city using the citipy module.

# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

768

In [9]:
# 5. Perform an API call with the OpenWeatherMap.

# Starting URL for Weather Map API Call.
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [10]:
# 6. Retrieve the following information from the API call:
# Latitude and longitude
# Maximum temperature
# Percent humidity
# Percent cloudiness
# Wind speed
# Weather description (for example, clouds, fog, light rain, clear sky)



# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1

# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
# Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_description = city_weather["weather"][0]["description"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Current Description": city_description,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | ushuaia
Processing Record 2 of Set 1 | narsaq
Processing Record 3 of Set 1 | saskylakh
Processing Record 4 of Set 1 | ilulissat
Processing Record 5 of Set 1 | castro
Processing Record 6 of Set 1 | rikitea
Processing Record 7 of Set 1 | atuona
Processing Record 8 of Set 1 | praia
Processing Record 9 of Set 1 | kondoa
Processing Record 10 of Set 1 | lompoc
Processing Record 11 of Set 1 | tsihombe
City not found. Skipping...
Processing Record 12 of Set 1 | hermanus
Processing Record 13 of Set 1 | butaritari
Processing Record 14 of Set 1 | belushya guba
City not found. Skipping...
Processing Record 15 of Set 1 | mpulungu
City not found. Skipping...
Processing Record 16 of Set 1 | barrow
Processing Record 17 of Set 1 | lata
Processing Record 18 of Set 1 | port lincoln
Processing Record 19 of Set 1 | east london
Processing Record 20 of Set 1 | airai
Processing Record 21 of Set 1 | barentsburg
City not found. Skipping...
Processing Record 22 of Set 1 | khatanga
Processing Record 23 of Set 1 | tuktoyaktuk
Processing Record 24 of Set 1 | yellowknife
Processing Record 25 of Set 1 | digha
Processing Record 26 of Set 1 | bangassou
Processing Record 27 of Set 1 | khandyga
Processing Record 28 of Set 1 | carnarvon
Processing Record 29 of Set 1 | busselton
Processing Record 30 of Set 1 | klaksvik
Processing Record 31 of Set 1 | mokhsogollokh
Processing Record 32 of Set 1 | punta arenas
Processing Record 33 of Set 1 | tasiilaq
Processing Record 34 of Set 1 | lavrentiya
Processing Record 35 of Set 1 | saldanha
Processing Record 36 of Set 1 | beyneu
City not found. Skipping...
Processing Record 37 of Set 1 | new norfolk
Processing Record 38 of Set 1 | bluff
Processing Record 39 of Set 1 | abnub
Processing Record 40 of Set 1 | lebu
Processing Record 41 of Set 1 | vaitupu
City not found. Skipping...
Processing Record 42 of Set 1 | humaita
Processing Record 43 of Set 1 | zyryanka
Processing Record 44 of Set 1 | meyungs
City not found. Skipping...
Processing Record 45 of Set 1 | sumter
Processing Record 46 of Set 1 | louis trichardt
Processing Record 47 of Set 1 | flinders
Processing Record 48 of Set 1 | marzuq
Processing Record 49 of Set 1 | pisco
Processing Record 50 of Set 1 | zhigansk

KeyboardInterrupt:

In [ ]:
#Unintentionally reran kernal during github upload review up to this point after already completing deliverables 1, 2, and 3. I interrupted the kernel from continuing after running the above block of code and saved here as to not affect the remainder of the project and the .csv file that was originally produced at the end of this notebook.

In [54]:
#used above to figure out how to add current description from 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}]
print(requests.get(city_url).json())

{'coord': {'lon': -50.0119, 'lat': -24.7911}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'base': 'stations', 'main': {'temp': 55.78, 'feels_like': 55.42, 'temp_min': 55.78, 'temp_max': 55.78, 'pressure': 1021, 'humidity': 93, 'sea_level': 1021, 'grnd_level': 907}, 'visibility': 10000, 'wind': {'speed': 4.07, 'deg': 61, 'gust': 5.1}, 'clouds': {'all': 4}, 'dt': 1658369181, 'sys': {'country': 'BR', 'sunrise': 1658311340, 'sunset': 1658350205}, 'timezone': -10800, 'id': 3466704, 'name': 'Castro', 'cod': 200}

In [92]:
# 7. Add the data to a new DataFrame.
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head()

,City,Lat,Lng,Current Description,Max Temp,Humidity,Cloudiness,Wind Speed,Country
0,Bluff,-46.6000,168.3333,overcast clouds,45.81,69,100,7.49,NZ
1,Monte Alegre,-2.0078,-54.0692,scattered clouds,74.37,91,35,3.89,BR
2,Yerofey Pavlovich,53.9667,121.9667,overcast clouds,72.41,69,93,3.27,RU
3,Talcahuano,-36.7167,-73.1167,light intensity drizzle,51.48,100,100,8.05,CL
4,Hithadhoo,-0.6000,73.0833,overcast clouds,79.88,76,99,5.66,MV

In [93]:
# 7.
new_column_order = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description"]
city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Bluff,NZ,-46.6000,168.3333,45.81,69,100,7.49,overcast clouds
1,Monte Alegre,BR,-2.0078,-54.0692,74.37,91,35,3.89,scattered clouds
2,Yerofey Pavlovich,RU,53.9667,121.9667,72.41,69,93,3.27,overcast clouds
3,Talcahuano,CL,-36.7167,-73.1167,51.48,100,100,8.05,light intensity drizzle
4,Hithadhoo,MV,-0.6000,73.0833,79.88,76,99,5.66,overcast clouds
5,Port Elizabeth,ZA,-33.9180,25.5701,54.32,92,40,13.00,scattered clouds
6,Tuatapere,NZ,-46.1333,167.6833,46.76,79,100,5.03,overcast clouds
7,Bethel,US,41.3712,-73.4140,81.66,77,1,1.01,clear sky
8,Nemuro,JP,43.3236,145.5750,60.91,85,56,8.68,broken clouds
9,Alamosa,US,37.4695,-105.8700,75.18,38,40,12.66,scattered clouds

In [94]:
# format "Lat" and "Lng" to two decimal places
city_data_df["Lat"] = city_data_df["Lat"].map("{:.2f}".format)
city_data_df["Lng"] = city_data_df["Lng"].map("{:.2f}".format)  
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Bluff,NZ,-46.60,168.33,45.81,69,100,7.49,overcast clouds
1,Monte Alegre,BR,-2.01,-54.07,74.37,91,35,3.89,scattered clouds
2,Yerofey Pavlovich,RU,53.97,121.97,72.41,69,93,3.27,overcast clouds
3,Talcahuano,CL,-36.72,-73.12,51.48,100,100,8.05,light intensity drizzle
4,Hithadhoo,MV,-0.60,73.08,79.88,76,99,5.66,overcast clouds
5,Port Elizabeth,ZA,-33.92,25.57,54.32,92,40,13.00,scattered clouds
6,Tuatapere,NZ,-46.13,167.68,46.76,79,100,5.03,overcast clouds
7,Bethel,US,41.37,-73.41,81.66,77,1,1.01,clear sky
8,Nemuro,JP,43.32,145.57,60.91,85,56,8.68,broken clouds
9,Alamosa,US,37.47,-105.87,75.18,38,40,12.66,scattered clouds

In [95]:
# Export the DataFrame as a CSV file, 
# and save it as WeatherPy_Database.csv in the Weather_Database folder.

# Create the output file (CSV).
output_data_file = "../Weather_Database/WeatherPy_Database.csv"

# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")